CREATE TABLE TAB_FATURAMENTO
( 	DATA_VENDA DATE NULL,
	TOTAL_VENDA FLOAT);

INSERT INTO VENDAS_SUCOS.vendedores
(SELECT  MATRICULA
		,NOME
        ,BAIRRO
        ,PERCENTUAL_COMISSAO AS COMISSAO
        ,DATA_ADMISSAO
        ,DE_FERIAS AS FERIAS
FROM sucos_vendas.tabela_de_vendedores);

ALTER TABLE ITENS_NOTAS
MODIFY COLUMN CODIGO_PRODUTO VARCHAR(10);


SELECT * FROM tab_faturamento;
SELECT * FROM NOTAS;
SELECT * FROM ITENS_NOTAS;

SELECT * FROM CLIENTES; -- 1471156710
SELECT * FROM VENDEDORES; -- 00236
SELECT * FROM PRODUTOS; -- '1004327' '1002334'

INSERT INTO NOTAS
VALUES
('100', '2021-02-11', '1471156710', '00236', 0.03);
INSERT INTO ITENS_NOTAS
VALUES
('100', '1004327', 100, 10);
INSERT INTO ITENS_NOTAS
VALUES
('100', '1002334', 100, 10);

INSERT INTO NOTAS
VALUES
('101', '2021-02-11', '1471156710', '00236', 0.03);
INSERT INTO ITENS_NOTAS
VALUES
('101', '1004327', 100, 10);
INSERT INTO ITENS_NOTAS
VALUES
('101', '1002334', 100, 10);

INSERT INTO NOTAS
VALUES
('102', '2021-02-11', '1471156710', '00236', 0.03);
INSERT INTO ITENS_NOTAS
VALUES
('102', '1004327', 100, 10);
INSERT INTO ITENS_NOTAS
VALUES
('102', '1002334', 100, 10);


DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT 	NF.DATA AS DATA_VENDA
		,SUM(INF.QUANTIDADE * INF.PRECO)
FROM NOTAS NF
INNER JOIN ITENS_NOTAS INF
ON NF.NUMERO = INF.NUMERO; 


SELECT * FROM TAB_FATURAMENTO;

/* -------------- CRIANDO A TRIGGER ----------------------*/
-- DROP TRIGGER TG_CALCULA_FATURAMENTO
DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_INSERT AFTER INSERT ON ITENS_NOTAS
FOR EACH ROW 
BEGIN
	DELETE FROM TAB_FATURAMENTO;
	INSERT INTO TAB_FATURAMENTO
	SELECT 	NF.DATA AS DATA_VENDA
		,SUM(INF.QUANTIDADE * INF.PRECO)
	FROM NOTAS NF
	INNER JOIN ITENS_NOTAS INF
	ON NF.NUMERO = INF.NUMERO; 
END//

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_UPDATE AFTER UPDATE ON ITENS_NOTAS
FOR EACH ROW 
BEGIN
	DELETE FROM TAB_FATURAMENTO;
	INSERT INTO TAB_FATURAMENTO
	SELECT 	NF.DATA AS DATA_VENDA
		,SUM(INF.QUANTIDADE * INF.PRECO)
	FROM NOTAS NF
	INNER JOIN ITENS_NOTAS INF
	ON NF.NUMERO = INF.NUMERO; 
END//

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_DELETE AFTER DELETE ON ITENS_NOTAS
FOR EACH ROW 
BEGIN
	DELETE FROM TAB_FATURAMENTO;
	INSERT INTO TAB_FATURAMENTO
	SELECT 	NF.DATA AS DATA_VENDA
		,SUM(INF.QUANTIDADE * INF.PRECO)
	FROM NOTAS NF
	INNER JOIN ITENS_NOTAS INF
	ON NF.NUMERO = INF.NUMERO; 
END//

DELETE FROM ITENS_NOTAS;
DELETE FROM NOTAS;


/* TRIGGER PARA ATUALIZAR IDADE DO CLIENTE APOS UM INSERT */
SELECT *
FROM CLIENTES;

SELECT 	CPF
		, IDADE
        , DATA_NASCIMENTO
        , timestampdiff(YEAR, DATA_NASCIMENTO, NOW())  
FROM CLIENTES

DROP TRIGGER TG_CLIENTES_IDADE_INSERT

DELIMITER //
CREATE TRIGGER TG_CLIENTES_IDADE_INSERT BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
	SET NEW.IDADE = timestampdiff(YEAR, NEW.DATA_NASCIMENTO, NOW());
END//


INSERT INTO `vendas_sucos`.`clientes`
(`CPF`,
`NOME`,
`ENDERECO`,
`BAIRRO`,
`CIDADE`,
`ESTADO`,
`CEP`,
`DATA_NASCIMENTO`,
`IDADE`,
`SEXO`,
`LIMITE_CREDITO`,
`VOLUME_COMPRA`,
`PRIMEIRA_COMPRA`)
VALUES
(	'731687427'
	,'TESTE'
    ,'R. Dois de Fevereiro'
    , 'Água Santa'
    , 'Rio de Janeiro'
    , 'RJ', '22000000'
    , '1993-09-15'
    , 18
    , 'M'
    , 100000
    , 20000
    , 1);






