CREATE DATABASE [VENDAS SUCO]

CREATE DATABASE [VENDAS SUCOS 2]
ON( NAME= VENDAS_SUCOS_2_DAT
	,FILENAME = 'C:\repositorios-github\VENDAS_SUCOS_2.MDF'
	,SIZE = 10
	,MAXSIZE = 50
	,FILEGROWTH = 2)
LOG ON(	NAME = VENDAS_SUCOS_2_LOG
		,FILENAME = 'C:\repositorios-github\VENDAS_SUCOS_2.LDF'
		,SIZE = 10
		,MAXSIZE = 50
		,FILEGROWTH = 5)

DROP DATABASE [VENDAS SUCOS 2];