--DROP TABLE [NOTAS];
--DROP TABLE [ITENS VENDIDOS];
--DROP TABLE [PRODUTO];
--DROP TABLE [VENDEDORES];
--DROP TABLE [CLIENTE];



CREATE TABLE [PRODUTO]
(	 [CODIGO] VARCHAR(10) NOT NULL
	,[DESCRITOR] VARCHAR(100) NULL
	,[SABOR] VARCHAR(50) NULL
	,[TAMANHO] VARCHAR(50) NULL
	,[EMBALAGEM] VARCHAR(50) NULL
	,[PRECOLISTA] FLOAT NULL
	,CONSTRAINT [PK_PRODUTO] PRIMARY KEY([CODIGO]));


CREATE TABLE [VENDEDORES]
(	 [MATRICULA] VARCHAR(5) NOT NULL
	,[NOME] VARCHAR(100) NULL
	,[BAIRRO] VARCHAR(50) NULL
	,[COMISSA] FLOAT NULL
	,[DTADMISSAO] DATE NULL
	,[FERIAS] BIT NULL
	,CONSTRAINT [PK_VENDEDORES] PRIMARY KEY([MATRICULA]));

CREATE TABLE [CLIENTE]
(	 [CPF] VARCHAR(11) NOT NULL
	,[NOME] VARCHAR(100) NULL
	,[ENDERECO] VARCHAR(150) NULL
	,[BAIRRO] VARCHAR(50) NULL
	,[CIDADE] VARCHAR(50) NULL
	,[ESTADO] VARCHAR(50) NULL
	,[CEP] VARCHAR(8) NULL
	,[DTNASCIMENTO] DATE NULL
	,IDADE SMALLINT NULL
	,[SEXO] VARCHAR(1) NULL
	,[LIMCREDITO] FLOAT NULL
	,[VOLCOMPRA ]FLOAT NULL
	,[PRICOMPRA ]BIT NULL
	,CONSTRAINT [PK_CLIENTE] PRIMARY KEY ([CPF]));

CREATE TABLE [NOTAS]
(	 [NUMERO] VARCHAR(5) NOT NULL
	,[DATA] DATE NULL
	,[CPF] VARCHAR(11) NULL
	,[MATRICULA] VARCHAR(5) NULL
	,[IMPOSTO] FLOAT NULL
	,CONSTRAINT [PK_NOTAS] PRIMARY KEY([NUMERO]));

ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_CLIENTE]
FOREIGN KEY([CPF]) REFERENCES [CLIENTE]([CPF]);

ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_VENDEDORES]
FOREIGN KEY([MATRICULA]) REFERENCES [VENDEDORES]([MATRICULA]);

CREATE TABLE [ITENS VENDIDOS]
(	 [NUMERO] VARCHAR(5) NOT NULL
	,[CODPRODUTO] VARCHAR(10) NULL
	,QUANTIDADE INT NULL
	,PRECO FLOAT NULL
	,CONSTRAINT [PK_ITENS_VENDIDOS] PRIMARY KEY([NUMERO]));

ALTER TABLE [ITENS VENDIDOS] WITH CHECK ADD CONSTRAINT[FK_ITENS_NOTAS]
FOREIGN KEY([NUMERO]) REFERENCES [NOTAS]([NUMERO]);

ALTER TABLE [ITENS VENDIDOS] WITH CHECK ADD CONSTRAINT[FK_ITENS_PRODUTO]
FOREIGN KEY([CODPRODUTO]) REFERENCES [PRODUTO]([CODIGO]);